export const ADD_FAVORITE = "ADD_FAVORITE"
export const DELETE_FAVORITE = "DELETE_FAVORITE"
export const CLEAN_FAVORITE = "CLEAN_FAVORITE"
export const FILTER = "FILTER"
export const ORDER = "ORDER"
export const UNFILTER = "UNFILTER"